config/routes.rb
Splurty::Application.routes.draw do
  root 'quotes#index'

  resources :quotes
  get 'about', :to => 'quotes#about'
  

end

app/models/quote.rb
class Quote < ActiveRecord::Base
	validates :saying, :presence => true, :length => { :maximum => 140, :minimum => 3 }
	validates :author, :presence => true, :length => { :maximum => 50, :minimum => 3 }

	def unique_tag
		abbr = self.author.split(" ").collect do |sub_string|
			sub_string[0]
	end

	abbr.join + '#' + self.id.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	def index
		@quote = Quote.order("RANDOM()").first
	end

	def create
		@quote = Quote.create(quote_params)
		if @quote.invalid?
			flash[:error] = '<strong>Could not save.</strong> The data you entered is invalid.'
		end
		redirect_to root_path
	end

	def about
	end

	def show
		@quote = Quote.where(:id => params[:id]).first
		if @quote.blank?
			render :text => "Not Found", :status => :not_found
		end
	end

	private

	def quote_params
		params.require(:quote).permit(:saying, :author)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Twainerator</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
	<header>
		<div class="col-xs-3">
		<%= link_to root_path, :class => 'logo' do %>
			<div class="circle">
  				<br />
  				Mark
  				<br />
  				Twain's
  				<br />
  				Twainerator
			</div>
		<% end %>
		</div>
		<div class="col-sm-4 hidden-xs slogan">
			Quoting random, declarative statements from a master intellect.
		</div>
		<div class="col-xs-8 col-xs-offset-1 col-sm-offset-0 col-sm-5 links">
			<!-- Button trigger modal -->
			<%= link_to 'Contribute', '#', :data => {:toggle => 'modal', :target => '#myModal'} %>
			&nbsp;
			&nbsp;
			&nbsp;
			<%= link_to 'About', about_path %>
		</div>
	</header>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Contribute Your Quote</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for Quote.new do |f| %>
			<%= f.input :saying, :label => "Google 'Mark Twain quotes' for some inspiration!", :placeholder => "e.g., Be good and you will be lonesome." %>
			<br />
			<%= f.input :author, :label => "Author", :placeholder => "Mark Twain" %>
		</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Create", :class => "btn btn-danger btn-md" %>
      </div>
		<% end %>
    </div>
  </div>
</div>

	<hr />
	<br class="clear" /> 

<div class="container">
	<% if flash[:error].present? %>
		<div class="col-xs-10 col-xs-offset-1 alert alert-danger">
			<%= flash[:error].html_safe %>
		</div>
		<br class="clear" />
	<% end %>
	<%= yield %>
</div>

<div class="footer">
	<div class="container">
		<div class="col-xs-12 col-sm-6">
			<%= link_to "I need more Twaineration!", root_path, :class => 'next-quote' %>
		</div>
		<div class="col-xs-12 col-sm-6 footer-blurb">
			Proudly hacked in New York, NY by <a href="http://www.ericandrade.com">Eric Andrade</a>.<br />
			If you want to learn how to build your own Web App - <a href="http://thefirehoseproject.com">Learn how to code here.</a>
		</div>
	</div>
</div>

</body>
</html>

app/views/quotes/about.html.erb
<div class="col-xs-10 col-xs-offset-1" about>
	<h1>About The Twainerator</h1>

	<p>
		The Twainerator was built by <a target="_blank" href="https://github.com/buddhaplex">Eric Andrade</a>, a fledgling developer with a long history in managing technology-driven marketing solutions for many clients. 
	</p>
		<p>
			Eric is an avid reader, and a huge fan of Mark Twain's witticisms and insights. He's sharing some of his favorite Mark Twain quotes here, but also looking for you to share yours, if you don't see one that you particularly like. 
		</p>
		<p>
			If you want to know more about Eric, you can visit his <a target="_blank" href="http://www.ericandrade.com">website here</a>.
		</p>
		<br />

		<div class="col-xs-12 col-sm-4">
			<%= image_tag 'eric.jpg', :class => 'img-responsive' %>
		</div>

		<div class="col-xs-12 col-sm-7 col-sm-offset-1">
			<h2 class="text-center">Eric Andrade</h2>
			<br />
			<p>
				Eric Andrade is an agency operations executive, web developer, and product manager. Over the course of his career, he has worked as a copywriter, producer, user experience professional, client service lead, and business strategy professional. In 2014, he led the production and development of Samsung CenterStage, an innovative digital at retail installation that has since won two prestigious Advertising awards: The One Show, and a Cannes Lion. You can find out more about the <a target="_blank" href="http://www.ericandrade.com/work#/samsung-centerstage/">project here</a>.
			</p>
		</div>
		<br class="clear" />
		<br />
		<br />
		<br />
		<br />


</div>

app/views/quotes/index.html.erb
<h2>
	<span>Twaineration / No. <%= @quote.unique_tag %></span>
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="pull-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />

app/views/quotes/show.html.erb
<h2>
  <span>SPLURTY / <%= @quote.unique_tag %></span>
  Here's the <u>best unsolicited startup advice</u> you can get!
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="pull-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />